"""create core learning tables

Revision ID: 49daaae7a91d
Revises: 
Create Date: 2026-10-07 22:05:24.864923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49daaae7a91d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_accounts_email'), ['email'], unique=True)

    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('age_group', sa.String(length=30), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('curriculum_profile', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_parent_id'), ['parent_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=True),
    sa.Column('concept_code', sa.String(length=100), nullable=True),
    sa.Column('current_problem', sa.Text(), nullable=True),
    sa.Column('current_hint_level', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('direct_answer_requests', sa.Integer(), nullable=False),
    sa.Column('current_misconception', sa.String(length=150), nullable=True),
    sa.Column('mastery_state', sa.String(length=30), nullable=False),
    sa.Column('last_tutor_action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_sessions_subject'), ['subject'], unique=False)

    op.create_table('mastery_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('concept_code', sa.String(length=100), nullable=False),
    sa.Column('mastery_state', sa.String(length=30), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('independent_successes', sa.Integer(), nullable=False),
    sa.Column('assisted_successes', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('follow_up_successes', sa.Integer(), nullable=False),
    sa.Column('explain_back_successes', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'concept_code', name='uq_student_concept_mastery')
    )
    with op.batch_alter_table('mastery_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_records_student_id'), ['student_id'], unique=False)

    op.create_table('student_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('problem_ref', sa.String(length=100), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_independent', sa.Boolean(), nullable=False),
    sa.Column('hint_level_before', sa.Integer(), nullable=False),
    sa.Column('misconception_code', sa.String(length=100), nullable=True),
    sa.Column('validator_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attempts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('tutor_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('detected_intent', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('attempt_status', sa.String(length=30), nullable=True),
    sa.Column('selected_action', sa.String(length=100), nullable=False),
    sa.Column('selected_hint_level', sa.Integer(), nullable=False),
    sa.Column('allow_final_answer', sa.Boolean(), nullable=False),
    sa.Column('requires_rag', sa.Boolean(), nullable=False),
    sa.Column('requires_validation', sa.Boolean(), nullable=False),
    sa.Column('requires_mastery_check', sa.Boolean(), nullable=False),
    sa.Column('policy_bypass_detected', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_decisions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutor_decisions_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_decisions_student_id'))
        batch_op.drop_index(batch_op.f('ix_tutor_decisions_session_id'))

    op.drop_table('tutor_decisions')
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_attempts_session_id'))

    op.drop_table('student_attempts')
    with op.batch_alter_table('mastery_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mastery_records_student_id'))

    op.drop_table('mastery_records')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sessions_subject'))
        batch_op.drop_index(batch_op.f('ix_learning_sessions_student_id'))

    op.drop_table('learning_sessions')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_parent_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('parent_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_accounts_email'))

    op.drop_table('parent_accounts')
    # ### end Alembic commands ###
