from enum import Enum


class AgeGroup(str, Enum):
    FOUNDATION = "FOUNDATION"
    DEVELOPING = "DEVELOPING"
    INDEPENDENT = "INDEPENDENT"


class Subject(str, Enum):
    MATH = "MATH"
    ENGLISH = "ENGLISH"
    SCIENCE = "SCIENCE"
    GENERAL = "GENERAL"


class LearningMode(str, Enum):
    LEARN = "LEARN"
    HOMEWORK_HELP = "HOMEWORK_HELP"
    PRACTICE = "PRACTICE"
    MOCK_TEST = "MOCK_TEST"
    VOICE = "VOICE"


class AttemptStatus(str, Enum):
    CORRECT = "CORRECT"
    PARTIALLY_CORRECT = "PARTIALLY_CORRECT"
    INCORRECT = "INCORRECT"
    INCOMPLETE = "INCOMPLETE"
    UNCLEAR = "UNCLEAR"


class MasteryState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    LEARNING = "LEARNING"
    DEVELOPING = "DEVELOPING"
    STRONG = "STRONG"


class SessionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class TutorIntent(str, Enum):
    LEARN_CONCEPT = "LEARN_CONCEPT"

    HOMEWORK_REQUEST = "HOMEWORK_REQUEST"

    STUDENT_ATTEMPT = "STUDENT_ATTEMPT"

    HINT_REQUEST = "HINT_REQUEST"

    DIRECT_ANSWER_REQUEST = "DIRECT_ANSWER_REQUEST"

    EXPLANATION_REQUEST = "EXPLANATION_REQUEST"

    PRACTICE_REQUEST = "PRACTICE_REQUEST"

    MOCK_TEST_RESPONSE = "MOCK_TEST_RESPONSE"

    CONFUSION = "CONFUSION"

    I_DONT_KNOW = "I_DONT_KNOW"

    POLICY_BYPASS = "POLICY_BYPASS"

    OFF_TOPIC = "OFF_TOPIC"

    SAFETY_SENSITIVE = "SAFETY_SENSITIVE"


class TutorAction(str, Enum):
    ASK_ATTEMPT = "ASK_ATTEMPT"

    ASK_PRIOR_KNOWLEDGE = "ASK_PRIOR_KNOWLEDGE"

    ASK_GUIDING_QUESTION = "ASK_GUIDING_QUESTION"

    GIVE_HINT = "GIVE_HINT"

    GIVE_SIMILAR_EXAMPLE = "GIVE_SIMILAR_EXAMPLE"

    BREAK_INTO_STEPS = "BREAK_INTO_STEPS"

    GIVE_STRONG_GUIDANCE = "GIVE_STRONG_GUIDANCE"

    GIVE_FULL_TEACHING_EXPLANATION = (
        "GIVE_FULL_TEACHING_EXPLANATION"
    )

    EVALUATE_ATTEMPT = "EVALUATE_ATTEMPT"

    ASK_RETRY = "ASK_RETRY"

    ASK_EXPLAIN_BACK = "ASK_EXPLAIN_BACK"

    GIVE_MASTERY_QUESTION = "GIVE_MASTERY_QUESTION"

    GIVE_FEEDBACK = "GIVE_FEEDBACK"

    SWITCH_TO_PREREQUISITE = "SWITCH_TO_PREREQUISITE"

    ESCALATE_SAFETY = "ESCALATE_SAFETY"

    REFUSE_POLICY_BYPASS = "REFUSE_POLICY_BYPASS"

    GENERATE_PRACTICE_QUESTION = "GENERATE_PRACTICE_QUESTION"

    RECORD_TEST_RESPONSE = "RECORD_TEST_RESPONSE"

    CLARIFY_TEST_INSTRUCTION = "CLARIFY_TEST_INSTRUCTION"

    REDIRECT_TO_LEARNING = "REDIRECT_TO_LEARNING"